version: '3'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: review-node
    ports:
      - ${NODE_PORT}:3000
    command: node
    volumes:
      - source-repository:/home/node/app
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: review-php
    ports:
      - ${PHP_PORT}:80
    volumes:
      - source-repository:/var/www/html
    links:
      - mysql
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: review-mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: bit_academy
      MYSQL_PASSWORD: bit_academy
    volumes:
      - source-repository:/home

volumes:
  source-repository:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REPO_SOURCE}